server:
  port: ${PORT:3003}

spring:
  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:postgresql://localhost:5432/nlmk_test}
    username: ${DB_USERNAME:roman}
    password: ${DB_PASSWORD:}
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

springdoc:
  swagger-ui:
    path: /api/docs
  api-docs:
    path: /api/openapi.json

app:
  logs-dir: ${IMPORT_LOGS_DIR:backend/logs}
